/**
 * BulbaCourses.Podcasts.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { AudioWeb } from '../model/audioWeb';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AudioService {

    protected basePath = 'https://localhost:44366';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Adds audiodata to the database
     * 
     * @param audioWeb 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public audioCreate(audioWeb: AudioWeb, observe?: 'body', reportProgress?: boolean): Observable<AudioWeb>;
    public audioCreate(audioWeb: AudioWeb, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AudioWeb>>;
    public audioCreate(audioWeb: AudioWeb, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AudioWeb>>;
    public audioCreate(audioWeb: AudioWeb, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (audioWeb === null || audioWeb === undefined) {
            throw new Error('Required parameter audioWeb was null or undefined when calling audioCreate.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<AudioWeb>(`${this.basePath}/api/audios/Create`,
            audioWeb,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deletes audiodata in the database
     * 
     * @param audioWeb 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public audioDelete(audioWeb: AudioWeb, observe?: 'body', reportProgress?: boolean): Observable<AudioWeb>;
    public audioDelete(audioWeb: AudioWeb, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AudioWeb>>;
    public audioDelete(audioWeb: AudioWeb, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AudioWeb>>;
    public audioDelete(audioWeb: AudioWeb, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (audioWeb === null || audioWeb === undefined) {
            throw new Error('Required parameter audioWeb was null or undefined when calling audioDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.delete<AudioWeb>(`${this.basePath}/api/audios/Delete`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets all audiodata for course from the database
     * 
     * @param courseId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public audioGetAll(courseId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<AudioWeb>>;
    public audioGetAll(courseId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AudioWeb>>>;
    public audioGetAll(courseId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AudioWeb>>>;
    public audioGetAll(courseId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (courseId === null || courseId === undefined) {
            throw new Error('Required parameter courseId was null or undefined when calling audioGetAll.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<AudioWeb>>(`${this.basePath}/api/audios/GetFor/${encodeURIComponent(String(courseId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Gets audiodata from the database by id
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public audioGetById(id: string, observe?: 'body', reportProgress?: boolean): Observable<AudioWeb>;
    public audioGetById(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AudioWeb>>;
    public audioGetById(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AudioWeb>>;
    public audioGetById(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling audioGetById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AudioWeb>(`${this.basePath}/api/audios/Get/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all audios from the database that have substring in name
     * 
     * @param substring 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public audioSearch(substring: string, observe?: 'body', reportProgress?: boolean): Observable<Array<AudioWeb>>;
    public audioSearch(substring: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AudioWeb>>>;
    public audioSearch(substring: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AudioWeb>>>;
    public audioSearch(substring: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (substring === null || substring === undefined) {
            throw new Error('Required parameter substring was null or undefined when calling audioSearch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<AudioWeb>>(`${this.basePath}/api/audios/Search/${encodeURIComponent(String(substring))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Updates audiodata in the database
     * 
     * @param audioWeb 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public audioUpdate(audioWeb: AudioWeb, observe?: 'body', reportProgress?: boolean): Observable<AudioWeb>;
    public audioUpdate(audioWeb: AudioWeb, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AudioWeb>>;
    public audioUpdate(audioWeb: AudioWeb, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AudioWeb>>;
    public audioUpdate(audioWeb: AudioWeb, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (audioWeb === null || audioWeb === undefined) {
            throw new Error('Required parameter audioWeb was null or undefined when calling audioUpdate.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth2) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<AudioWeb>(`${this.basePath}/api/audios/Update`,
            audioWeb,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
