/**
 * BulbaCourses.Podcasts.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AudioWeb } from './audioWeb';
import { CommentWeb } from './commentWeb';
import { UserWeb } from './userWeb';


export interface CourseWeb { 
    id?: string;
    name?: string;
    author?: UserWeb;
    raiting?: number;
    description?: string;
    duration?: number;
    price?: number;
    creationDate?: Date;
    audios?: Array<AudioWeb>;
    comments?: Array<CommentWeb>;
}
