/**
 * BulbaCourses.Podcasts.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommentWeb } from './commentWeb';
import { CourseWeb } from './courseWeb';


export interface UserWeb { 
    id?: string;
    isAdmin?: boolean;
    name?: string;
    description?: string;
    email?: string;
    avatar?: string;
    registrationDate?: Date;
    uploadedCourses?: Array<CourseWeb>;
    boughtCourses?: Array<CourseWeb>;
    comments?: Array<CommentWeb>;
}
