// <auto-generated />
namespace BulbaCourses.Youtube.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_foreignKey_searchRequestId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_foreignKey_searchRequestId));
        
        string IMigrationMetadata.Id
        {
            get { return "202001110058086_added_foreignKey_searchRequestId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
