// <auto-generated />
namespace BulbaCourses.DiscountAggregator.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201912261254478_updateUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
