// <auto-generated />
namespace BulbaCourses.DiscountAggregator.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class conflict : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(conflict));
        
        string IMigrationMetadata.Id
        {
            get { return "202001101119353_conflict"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
